### ISSUE TITLE
Configure backups for RDPC DEV/QA and PROD envs

### ISSUE THREAD

**Issue by yalturmes** [overture-stack/maestro#163] opened 2020-08-06 20:44 UTC
- [x] Configure Jenkins Thin backup plugin and storage
- [ ] Configure off-site backup

**Comment by akachru-github** [comment] 2020-08-07 14:34
Duplicate of 
https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/310

closing.

**Closed by akachru-github** 2020-08-07 14:34 UTC
Labels: devops, wont-do
